### PR TITLE
Update master

### PR DESCRIPTION
**Pull request by slaroche**
@isra17 and @aviau 

I want to update the flare fork of the project to the original one. Then I will rebase the branche flared on master and tag it `5.2.1`.

The goal of doing this is to bump the flask dependency to be above `2.0.0`.

### CODE REVIEW

**Comment by aviau** [comment]
Sure, did you test?

**Comment by slaroche** [comment]
The CI is passing, I can try to run the tests.

I wil update the description to define my intention.

**Comment by aviau** [comment]
I mean did you test relogin?

**Comment by slaroche** [comment]
I don't think relogin use `Flared/master`. Should rebase `Flared/flared` on `mitmproxy/main`?

**Comment by aviau** [comment]
It does not use any specific branch. It uses a specific commit. Just point it to this commit.

**Comment by aviau** [comment]
Also this repository used to have a single commit based on top of master. It looks like max changed that. Can you please fix it?

**Comment by aviau** [comment]
This should be the only commit on top of master, and we should never do any merges:
- https://github.com/Flared/mitmproxy/commit/882d7bafbf41703d033c1bca150d541e1035c09a

**Comment by slaroche** [comment]
ok then, this is my fix that I want you to review:
- reset HEAD~1 to remove max commit
- git rebase upstream/main
- git push --force on `Flared/flared`
- ~~fetch upstream (in gitlab interface on `Flared/flared`)~~

this should bump `protobuf` and `flask` dependency.

**Comment by aviau** [comment]
everything will be perfect

**Pull request closed without merging**
